version: "3.1"

services:
  db:
    image: mongo
    profiles:
      - dev
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test1
      MONGO_INITDB_ROOT_PASSWORD: pass1
      MONGO_INITDB_DATABASE: test_db

  api:
    profiles:
      - dev
    build:
      context: .
      target: base
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      DB_USER: test1
      DB_PASSWORD: pass1
      DB_URL: mongodb://test1:pass1@db:27017
volumes:
  code:
